Add Deliverance
SpaceTradersAPI/awesome-spacetraders pull request #3
Opened 2021-03-09 23:17 UTC by Stumblinbear

2021-03-09 23:42 UTC, jadlers requested changes
Congrats on submitting the first PR! :tada: 

Some changes needed before I can merge it:
1. A tiny modification needed in the readme addition.
2. You need to add instructions on how to get your project up and running in your repository. Preferably in its readme.

2021-03-09 23:42 UTC, jadlers commented on README.md
> +* [Deliverance](https://github.com/Stumblinbear/Deliverance) - VueJS-based web interface for Space Traders
Please end the line with a period "." as per the the [contribution guidelines](https://github.com/SpaceTradersAPI/awesome-spacetraders/blob/main/contributing.md).

2021-03-09 23:59 UTC, artokun commented
Can we nest this under Typescript too?

2021-03-10 00:04 UTC, jadlers commented
@artokun at the moment I think it should be directly under client. The [contribution](https://github.com/SpaceTradersAPI/awesome-spacetraders/blob/main/contributing.md) guidelines says not to create a new subcategory before there is 3 items which belong under the category. This is to prevent too many subcategories from being made. Once there are a few TypeScript project we'll create the subcategory!

2021-03-10 00:06 UTC, Stumblinbear commented
It doesn't use Typescript, so it would have to be under Javascript or VueJS.

2021-03-10 00:09 UTC, jadlers approved these changes

2021-03-10 00:09 UTC, jadlers commented
Everything looks perfect! :ok_hand:

2021-03-10 00:09 UTC, merged